"""Homeowner scope questions, without company pricing or assumed selections."""

CHECKLIST_VERSION = '2026-09-17.1'

# Existing titles remain stable so saved source reviews still resolve.
# Each topic names the scope to verify, not work presumed required on every home.
_TOPICS = [
    ('site_work', 'Site work, driveway & final grading',
     ['site work','sitework','driveway','grading','excavat'],
     'What clearing, excavation, soil correction, driveway and final grading are included, and how are differing site conditions priced?'),
    ('gutters', 'Gutters & downspouts', ['gutter','downspout'],
     'Are gutters, downspouts and their drainage discharge included, and who supplies and installs them?'),
    ('low_voltage', 'Home technology, security & low-voltage', ['low volt','low-volt','structured wir','security','home tech'],
     'Do you want data wiring, security or other home technology? If selected, identify devices, wiring, installation and ongoing fees included.'),
    ('allowances', 'Every allowance defined in writing', ['allowance'],
     'For each allowance, what quantity, product level, labor, tax and delivery does it cover, and how are overages and unused balances handled?'),
    ('landscaping', 'Landscaping, sod & irrigation', ['landscap','sod','irrigation','seeding'],
     'What landscaping, ground cover and irrigation are included or left to the homeowner?'),
    ('insulation', 'Insulation matches the plan spec', ['insulat','spray foam','batt','encapsulat'],
     'What insulation products, R-values, wall/roof/floor boundaries, air sealing and crawlspace treatment are included, and how do they compare with the plans?'),
    ('lump_sums', 'No vague lump sums', [],
     'Which drawings, quantities, specifications, allowances and exclusions support each bundled trade price?'),
    ('change_orders', 'Change-order pricing is in the contract', ['change order','change-order','overage'],
     'How are scope changes authorized and priced, including markup, credits and schedule effects, before the work proceeds?'),
    ('framing', 'Framing materials and labor', ['framing','lumber','joist','truss'],
     'Does framing cover the selected floor and roof systems, beams, connectors, sheathing, backing and required equipment, including attic access and equipment platforms where shown?'),
    ('windows', 'Windows and exterior doors', ['window','exterior door','entry door'],
     'Which window and exterior-door units, sizes, glazing, hardware, flashing and installation are included, and who reconciles the supplier schedule to the plans?'),
    ('roofing', 'Roofing, flashing and ventilation', ['roofing','shingle','roof covering','flashing'],
     'Which roof covering, underlayment, flashing, penetrations and ventilation details are included, and who handles transitions to walls and chimneys?'),
    ('plumbing', 'Plumbing systems and fixtures', ['plumbing','water heater','plumbing fixture'],
     'What rough plumbing, fixtures, faucets, water heating, hose connections, testing and final installation are included, and which items are allowances or owner-supplied?'),
    ('electrical', 'Electrical service, wiring and fixtures', ['electrical','breaker panel','light fixture','receptacle'],
     'What electrical service, circuits, outlets, switches, lighting, alarms and final fixture installation are included, and which selections or service upgrades are extra?'),
    ('hvac', 'Heating, cooling and ventilation', ['hvac','heating','cooling','duct','heat pump'],
     'What equipment, design/sizing work, ducts, controls, ventilation, condensate disposal, testing and startup are included, and who coordinates power and access?'),
    ('cabinets', 'Cabinetry and storage', ['cabinet','vanity cabinet'],
     'Which kitchen, bath, laundry and storage cabinets, panels, fillers, hardware, delivery and installation are included in the final layout?'),
    ('flooring', 'Flooring materials and installation', ['flooring','lvp','carpet','hardwood'],
     'Which rooms, products, underlayment, preparation, transitions, waste and installation does the flooring price cover?'),
    ('cladding', 'Exterior cladding, masonry and trim', ['siding','cladding','brick','veneer','exterior trim'],
     'Which elevations and materials, weather barrier, flashing, masonry, trim, porch wraps and finish transitions are included?'),
    ('concrete', 'Slabs and concrete flatwork', ['slab','flatwork','concrete'],
     'Which slabs and flatwork, preparation, base, vapor barrier, reinforcement, thickened edges, finish, joints, pumping and placement labor are included?'),
    ('water_supply', 'Water supply and connections', ['well','water meter','water connection','water service'],
     'Will the home use a well or public water, and who pays for the source, service route, connection, testing, equipment and any required treatment?'),
    ('wastewater', 'Wastewater system and connections', ['septic','sewer','wastewater'],
     'Will the home use septic or sewer, and who covers design, approvals, installation, connection, testing and site restoration?'),
    ('foundation', 'Footings, foundation walls and moisture control', ['footing','footer','foundation','crawlspace','basement'],
     'What footing, wall, pier, reinforcement, fill, drainage, waterproofing or encapsulation scope is included for the specified foundation and site conditions?'),
    ('drywall', 'Drywall and finish level', ['drywall','sheetrock','gypsum'],
     'Which wall and ceiling areas, board thicknesses, wet-area or separation assemblies, finish level and texture are included?'),
    ('interior_trim', 'Interior doors, trim and hardware', ['interior door','interior trim','baseboard','molding','casing'],
     'Which door cores/styles, frames, pocket or bypass hardware, trim profiles, closets, stairs and installation are included?'),
    ('painting', 'Painting, staining and surface preparation', ['paint','stain','primer'],
     'Which interior/exterior surfaces, preparation, primer, finish coats, stain, caulking and final touchups are included?'),
    ('tile', 'Tile and wet-area waterproofing', ['tile','waterproof','shower pan'],
     'Which tile areas, substrates, shower waterproofing, drains, niches, edges, patterns and installation are included and coordinated with plumbing and glass?'),
    ('countertops', 'Countertops and fabrication', ['countertop','granite','quartz'],
     'Which tops, measured areas, material level, edges, cutouts, supports, backsplashes, templates and installation are included?'),
    ('garage_doors', 'Garage doors and openers', ['garage door','opener'],
     'If there is a garage, which doors, tracks, openers, controls, electrical connections and installation are included?'),
    ('fireplaces', 'Fireplaces, chimneys and venting', ['fireplace','chimney','hearth'],
     'If a fireplace is selected, what unit, venting/chimney, hearth, surround, fuel or power connection and startup are included?'),
    ('fuel_gas', 'Fuel gas piping and equipment', ['propane','gas line','gas piping','gas tank'],
     'If fuel gas is used, who supplies the tank or connection, piping, regulators, testing and appliance hookups, and are rental or fill charges separate?'),
    ('glass_mirrors', 'Shower glass and mirrors', ['shower glass','shower enclosure','mirror'],
     'Which glass enclosures, mirrors, hardware, measuring and installation are included or excluded?'),
    ('termite', 'Termite treatment and warranty', ['termite','pest treatment'],
     'What termite-treatment scope, timing, documentation, warranty and renewal responsibility are included for this property?'),
    ('cleaning', 'Construction cleanup and final cleaning', ['cleaning','cleanup','clean up'],
     'Who handles trade debris, protection, final interior/exterior cleaning, window cleaning and removal of remaining materials?'),
    ('appliances', 'Appliances, delivery and installation', ['appliance','range','refrigerator','dishwasher'],
     'Which appliances are builder- or owner-supplied, and who carries delivery, storage, installation, hookups and damage responsibility?'),
    ('decks_porches', 'Decks, porches, railings and fences', ['deck','porch','railing','fence'],
     'Which exterior platforms, stairs, guards/rails and any selected fencing are included, with their foundations, framing, decking, finishes and house connections?'),
    ('permits', 'Permits, inspections and project documents', ['permit','inspection','engineering','survey'],
     'Who obtains and pays for applicable plans, surveys, engineering, permits, inspections, testing and closeout documents, and which fees remain outside the bid?'),
    ('site_operations', 'Temporary services and construction operations', ['temporary','dumpster','portable toilet','mobilization'],
     'Who carries temporary power/water, sanitation, dumpsters, access, delivery handling, site protection and construction-duration charges?'),
]

PRE_BID_SCOPE_CHECKLIST = [
    {'id':identity,'title':title,'scope_keys':keys,'question':question,'detail':question,
     'category':'scope_confirmation','confidence':'needs_confirmation','detect':'scope',
     **({'optional_home_flag':'home_technology'} if identity=='low_voltage' else {})}
    for identity,title,keys,question in _TOPICS
]
